name: areej
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0 

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  firebase_core: ^3.9.0  
  firebase_auth: ^5.3.4 
  flutter_riverpod: ^2.6.1
  google_sign_in: ^6.2.2
  flutter_rating_bar: ^4.0.1
  flutter_easyloading: ^3.0.5
  flutter_timezone: ^4.0.0
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/img/
    - assets/font/

  # Fonts section
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/font/Metropolis-Medium.otf
        - asset: assets/font/Metropolis-Regular.otf
          weight: 500
        - asset: assets/font/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/font/Metropolis-Bold.otf
          weight: 700
        - asset: assets/font/Metropolis-ExtraBold.otf
          weight: 800
